#ifndef _SAVETREE_H
#define _SAVETREE_H

#include <TTree.h>
#include <TString.h>
#include "info.h"

class preTree
{
	public:
		preTree(TString name): myTTree(name, name) {};
		void write() {
			myTTree.Write();
		};
		void addGlobalBranch(Int_t &runNumber, Long_t &eventNumber, Int_t &helicity, Long_t &hipoIndex, Float_t &EBeam) {
			myTTree.Branch("runNumber", &runNumber, "runNumber/I");
			myTTree.Branch("eventNumber", &eventNumber, "eventNumber/L");
			myTTree.Branch("helicity", &helicity, "helicity/I");
			myTTree.Branch("hipoIndex", &hipoIndex, "hipoIndex/L");
    		myTTree.Branch("EBeam", &EBeam, "EBeam/F");
		};
		void addGlobalBranch(Int_t &runNumber, Long_t &eventNumber, Int_t &helicity, Long_t &hipoIndex, Int_t &isProton, Int_t &isMC, Int_t &isPreCut, Float_t &EBeam) {
			myTTree.Branch("runNumber", &runNumber, "runNumber/I");
			myTTree.Branch("eventNumber", &eventNumber, "eventNumber/L");
			myTTree.Branch("helicity", &helicity, "helicity/I");
			myTTree.Branch("hipoIndex", &hipoIndex, "hipoIndex/L");
    		myTTree.Branch("isProton", &isProton, "isProton/I");
    		myTTree.Branch("isMC", &isMC, "isMC/I");
    		myTTree.Branch("isPreCut", &isPreCut, "isPreCut/I");
    		myTTree.Branch("EBeam", &EBeam, "EBeam/F");
		};
		void addGlobalBranch(Int_t &runNumber, Long_t &eventNumber, Int_t &helicity, Long_t &hipoIndex, Int_t &isProton, Int_t &isMC, Int_t &isPreCut, Float_t &EBeam, Int_t &nElectron, Int_t &nNucleon, Int_t &nPhoton) {
			myTTree.Branch("runNumber", &runNumber, "runNumber/I");
			myTTree.Branch("eventNumber", &eventNumber, "eventNumber/L");
			myTTree.Branch("helicity", &helicity, "helicity/I");
			myTTree.Branch("hipoIndex", &hipoIndex, "hipoIndex/L");
    		myTTree.Branch("isProton", &isProton, "isProton/I");
    		myTTree.Branch("isMC", &isMC, "isMC/I");
    		myTTree.Branch("isPreCut", &isPreCut, "isPreCut/I");
    		myTTree.Branch("EBeam", &EBeam, "EBeam/F");
    		myTTree.Branch("nElectron", &nElectron, "nElectron/I");
    		myTTree.Branch("nNucleon", &nNucleon, "nNucleon/I");
    		myTTree.Branch("nPhoton", &nPhoton, "nPhoton/I");
		};
		void addGlobalBranch(Int_t &runNumber, Long_t &eventNumber, Int_t &helicity, Long_t &hipoIndex, Int_t &isMC, Float_t &EBeam, Int_t &nElectron, Int_t &nNucleon, Int_t &nPion, Int_t &nPhoton) {
			myTTree.Branch("runNumber", &runNumber, "runNumber/I");
			myTTree.Branch("eventNumber", &eventNumber, "eventNumber/L");
			myTTree.Branch("helicity", &helicity, "helicity/I");
			myTTree.Branch("hipoIndex", &hipoIndex, "hipoIndex/L");
			myTTree.Branch("isMC", &isMC, "isMC/I");
    		myTTree.Branch("EBeam", &EBeam, "EBeam/F");
    		myTTree.Branch("nElectron", &nElectron, "nElectron/I");
    		myTTree.Branch("nNucleon", &nNucleon, "nNucleon/I");
    		myTTree.Branch("nPion", &nPion, "nPion/I");
    		myTTree.Branch("nPhoton", &nPhoton, "nPhoton/I");
		};
		/*
		void addGlobalBranch(Int_t &runNumber, Long_t &eventNumber, Int_t &helicity, Long_t &hipoIndex, Float_t &EBeam, Int_t &nElectron, Int_t &nNucleon, Int_t &nPionP, Int_t &nPionM, Int_t &nPhoton) {
			myTTree.Branch("runNumber", &runNumber, "runNumber/I");
			myTTree.Branch("eventNumber", &eventNumber, "eventNumber/L");
			myTTree.Branch("helicity", &helicity, "helicity/I");
			myTTree.Branch("hipoIndex", &hipoIndex, "hipoIndex/L");
    		myTTree.Branch("EBeam", &EBeam, "EBeam/F");
    		myTTree.Branch("nElectron", &nElectron, "nElectron/I");
    		myTTree.Branch("nNucleon", &nNucleon, "nNucleon/I");
    		myTTree.Branch("nPionP", &nPionP, "nPionP/I");
    		myTTree.Branch("nPionM", &nPionM, "nPionM/I");
    		myTTree.Branch("nPhoton", &nPhoton, "nPhoton/I");
		};
		*/
		void addRecPartBranch(TString name, recParticle& paraPart) {
    		myTTree.Branch(name+"_pid", &paraPart.pid, name+"_pid/I");
    		myTTree.Branch(name+"_M", &paraPart.M, name+"_M/F");
    		myTTree.Branch(name+"_P", &paraPart.P, name+"_P/F");
    		myTTree.Branch(name+"_E", &paraPart.E, name+"_E/F");
    		myTTree.Branch(name+"_phi", &paraPart.phi, name+"_phi/F");
    		myTTree.Branch(name+"_theta", &paraPart.theta, name+"_theta/F");
    		myTTree.Branch(name+"_px", &paraPart.px, name+"_px/F");
    		myTTree.Branch(name+"_py", &paraPart.py, name+"_py/F");
    		myTTree.Branch(name+"_pz", &paraPart.pz, name+"_pz/F");
    		myTTree.Branch(name+"_vx", &paraPart.vx, name+"_vx/F");
    		myTTree.Branch(name+"_vy", &paraPart.vy, name+"_vy/F");
    		myTTree.Branch(name+"_vz", &paraPart.vz, name+"_vz/F");
    		myTTree.Branch(name+"_vt", &paraPart.vt, name+"_vt/F");
    		myTTree.Branch(name+"_charge", &paraPart.charge, name+"_charge/I");
    		myTTree.Branch(name+"_beta", &paraPart.beta, name+"_beta/F");
    		myTTree.Branch(name+"_chi2pid", &paraPart.chi2pid, name+"_chi2pid/F");
    		myTTree.Branch(name+"_status", &paraPart.status, name+"_status/I");
    		myTTree.Branch(name+"_pindex", &paraPart.pindex, name+"_pindex/I");
    		myTTree.Branch(name+"_mcindex", &paraPart.mcindex, name+"_mcindex/I");
		};
		void addMCPartBranch(TString name, mcParticle& paraPart) {
    		myTTree.Branch(name+"_pid", &paraPart.pid, name+"_pid/I");
    		myTTree.Branch(name+"_M", &paraPart.M, name+"_M/F");
    		myTTree.Branch(name+"_P", &paraPart.P, name+"_P/F");
    		myTTree.Branch(name+"_E", &paraPart.E, name+"_E/F");
    		myTTree.Branch(name+"_phi", &paraPart.phi, name+"_phi/F");
    		myTTree.Branch(name+"_theta", &paraPart.theta, name+"_theta/F");
    		myTTree.Branch(name+"_px", &paraPart.px, name+"_px/F");
    		myTTree.Branch(name+"_py", &paraPart.py, name+"_py/F");
    		myTTree.Branch(name+"_pz", &paraPart.pz, name+"_pz/F");
    		myTTree.Branch(name+"_vx", &paraPart.vx, name+"_vx/F");
    		myTTree.Branch(name+"_vy", &paraPart.vy, name+"_vy/F");
    		myTTree.Branch(name+"_vz", &paraPart.vz, name+"_vz/F");
    		myTTree.Branch(name+"_vt", &paraPart.vt, name+"_vt/F");
    		myTTree.Branch(name+"_mcindex", &paraPart.mcindex, name+"_mcindex/I");
    		myTTree.Branch(name+"_pindex", &paraPart.pindex, name+"_pindex/I");
		};
		void addSingleElBranch(TString name, singleEl& paraSingleEl) {
    		myTTree.Branch(name+"Q2", &paraSingleEl.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraSingleEl.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraSingleEl.Xbj, name+"Xbj/F");
		};
		void addDVCSBranch(TString name, DVCS& paraDVCS) {
    		myTTree.Branch(name+"Q2", &paraDVCS.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraDVCS.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraDVCS.Xbj, name+"Xbj/F");
    		myTTree.Branch(name+"t_nucleon", &paraDVCS.tNucleon, name+"t_nucleon/F");
    		myTTree.Branch(name+"t_photon", &paraDVCS.tPhoton, name+"t_photon/F");
    		myTTree.Branch(name+"delta_t", &paraDVCS.deltaT, name+"delta_t/F");
    		myTTree.Branch(name+"mM2_en2engX", &paraDVCS.mM2en2engX, name+"mM2_en2engX/F");
    		myTTree.Branch(name+"mP_en2engX", &paraDVCS.mPen2engX, name+"mP_en2engX/F");
    		myTTree.Branch(name+"mM2_en2enX", &paraDVCS.mM2en2enX, name+"mM2_en2enX/F");
    		myTTree.Branch(name+"mP_en2enX", &paraDVCS.mPen2enX, name+"mP_en2enX/F");
    		myTTree.Branch(name+"mM2_en2egX", &paraDVCS.mM2en2egX, name+"mM2_en2egX/F");
    		myTTree.Branch(name+"mP_en2egX", &paraDVCS.mPen2egX, name+"mP_en2egX/F");
    		myTTree.Branch(name+"mM2_en2ngX", &paraDVCS.mM2en2ngX, name+"mM2_en2ngX/F");
    		myTTree.Branch(name+"mP_en2ngX", &paraDVCS.mPen2ngX, name+"mP_en2ngX/F");
    		myTTree.Branch(name+"mM2_ed2engX", &paraDVCS.mM2ed2engX, name+"mM2_ed2engX/F");
    		myTTree.Branch(name+"mP_ed2engX", &paraDVCS.mPed2engX, name+"mP_ed2engX/F");
    		myTTree.Branch(name+"phi_nu_virPh", &paraDVCS.phiNuVirPh, name+"phi_nu_virPh/F");
    		myTTree.Branch(name+"phi_nu_outPh", &paraDVCS.phiNuOutPh, name+"phi_nu_outPh/F");
    		myTTree.Branch(name+"delta_phi", &paraDVCS.deltaPhi, name+"delta_phi/F");
    		myTTree.Branch(name+"theta_misPh_ph", &paraDVCS.thetaMisPhPh, name+"theta_misPh_ph/F");
    		myTTree.Branch(name+"theta_misNu_nu", &paraDVCS.thetaMisNuNu, name+"theta_misNu_nu/F");
    		myTTree.Branch(name+"theta_el_ph", &paraDVCS.thetaElPh, name+"theta_el_ph/F");
    		myTTree.Branch(name+"theta_el_nu", &paraDVCS.thetaElNu, name+"theta_el_nu/F");
    		myTTree.Branch(name+"theta_ph_nu", &paraDVCS.thetaPhNu, name+"theta_ph_nu/F");
    		myTTree.Branch(name+"exclusive_4DChi2", &paraDVCS.excl4DChi2, name+"exclusive_4DChi2/F");
		};
		void addDVpi0PBranch(TString name, DVpi0P& paraDVpi0P) {
    		myTTree.Branch(name+"pi0_px", &paraDVpi0P.pi0Px, name+"pi0_px/F");
    		myTTree.Branch(name+"pi0_py", &paraDVpi0P.pi0Py, name+"pi0_py/F");
    		myTTree.Branch(name+"pi0_pz", &paraDVpi0P.pi0Pz, name+"pi0_pz/F");
    		myTTree.Branch(name+"pi0_M", &paraDVpi0P.pi0M, name+"pi0_M/F");
    		myTTree.Branch(name+"pi0_P", &paraDVpi0P.pi0P, name+"pi0_P/F");
    		myTTree.Branch(name+"pi0_E", &paraDVpi0P.pi0E, name+"pi0_E/F");
    		myTTree.Branch(name+"pi0_phi", &paraDVpi0P.pi0Phi, name+"pi0_phi/F");
    		myTTree.Branch(name+"pi0_theta", &paraDVpi0P.pi0Theta, name+"pi0_theta/F");
    		myTTree.Branch(name+"pi0_openAng", &paraDVpi0P.pi0OpenAng, name+"pi0_openAng/F");
    		myTTree.Branch(name+"pi0_openAng0", &paraDVpi0P.pi0OpenAng0, name+"pi0_openAng0/F");
    		myTTree.Branch(name+"Q2", &paraDVpi0P.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraDVpi0P.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraDVpi0P.Xbj, name+"Xbj/F");
    		myTTree.Branch(name+"t_nucleon", &paraDVpi0P.tNucleon, name+"t_nucleon/F");
    		myTTree.Branch(name+"t_photon", &paraDVpi0P.tPhoton, name+"t_photon/F");
    		myTTree.Branch(name+"delta_t", &paraDVpi0P.deltaT, name+"delta_t/F");
    		myTTree.Branch(name+"mM2_en2enggX", &paraDVpi0P.mM2en2enggX, name+"mM2_en2enggX/F");
    		myTTree.Branch(name+"mP_en2enggX", &paraDVpi0P.mPen2enggX, name+"mP_en2enggX/F");
    		myTTree.Branch(name+"mM2_en2enX", &paraDVpi0P.mM2en2enX, name+"mM2_en2enX/F");
    		myTTree.Branch(name+"mP_en2enX", &paraDVpi0P.mPen2enX, name+"mP_en2enX/F");
    		myTTree.Branch(name+"mM2_en2eggX", &paraDVpi0P.mM2en2eggX, name+"mM2_en2eggX/F");
    		myTTree.Branch(name+"mP_en2eggX", &paraDVpi0P.mPen2eggX, name+"mP_en2eggX/F");
    		myTTree.Branch(name+"mM2_en2eng1X", &paraDVpi0P.mM2en2eng1X, name+"mM2_en2eng1X/F");
    		myTTree.Branch(name+"mP_en2eng1X", &paraDVpi0P.mPen2eng1X, name+"mP_en2eng1X/F");
    		myTTree.Branch(name+"mM2_en2eng2X", &paraDVpi0P.mM2en2eng2X, name+"mM2_en2eng2X/F");
    		myTTree.Branch(name+"mP_en2eng2X", &paraDVpi0P.mPen2eng2X, name+"mP_en2eng2X/F");
    		myTTree.Branch(name+"mM2_en2nggX", &paraDVpi0P.mM2en2nggX, name+"mM2_en2nggX/F");
    		myTTree.Branch(name+"mP_en2nggX", &paraDVpi0P.mPen2nggX, name+"mP_en2nggX/F");
    		myTTree.Branch(name+"mM2_ed2enggX", &paraDVpi0P.mM2ed2enggX, name+"mM2_ed2enggX/F");
    		myTTree.Branch(name+"mP_ed2enggX", &paraDVpi0P.mPed2enggX, name+"mP_ed2enggX/F");
    		myTTree.Branch(name+"phi_nu_virPh", &paraDVpi0P.phiNuVirPh, name+"phi_nu_virPh/F");
    		myTTree.Branch(name+"phi_nu_outPi0", &paraDVpi0P.phiNuOutPi0, name+"phi_nu_outPi0/F");
    		myTTree.Branch(name+"delta_phi", &paraDVpi0P.deltaPhi, name+"delta_phi/F");
    		myTTree.Branch(name+"theta_misPi0_pi0", &paraDVpi0P.thetaMisPi0Pi0, name+"theta_misPi0_pi0/F");
    		myTTree.Branch(name+"theta_misNu_nu", &paraDVpi0P.thetaMisNuNu, name+"theta_misNu_nu/F");
    		myTTree.Branch(name+"theta_el_ph1", &paraDVpi0P.thetaElPh1, name+"theta_el_ph1/F");
    		myTTree.Branch(name+"theta_el_ph2", &paraDVpi0P.thetaElPh2, name+"theta_el_ph2/F");
    		myTTree.Branch(name+"theta_el_nu", &paraDVpi0P.thetaElNu, name+"theta_el_nu/F");
    		myTTree.Branch(name+"theta_ph1_nu", &paraDVpi0P.thetaPh1Nu, name+"theta_ph1_nu/F");
    		myTTree.Branch(name+"theta_ph2_nu", &paraDVpi0P.thetaPh2Nu, name+"theta_ph2_nu/F");
    		myTTree.Branch(name+"theta_ph1_ph2", &paraDVpi0P.thetaPh1Ph2, name+"theta_ph1_ph2/F");
    		myTTree.Branch(name+"exclusive_4DChi2", &paraDVpi0P.excl4DChi2, name+"exclusive_4DChi2/F");
		};
		void addDVpipPBranch(TString name, DVpipP& paraDVpipP) {
    		myTTree.Branch(name+"Q2", &paraDVpipP.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraDVpipP.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraDVpipP.Xbj, name+"Xbj/F");
    		myTTree.Branch(name+"t_nucleon", &paraDVpipP.tNucleon, name+"t_nucleon/F");
    		myTTree.Branch(name+"t_photon", &paraDVpipP.tPhoton, name+"t_photon/F");
    		myTTree.Branch(name+"delta_t", &paraDVpipP.deltaT, name+"delta_t/F");
    		myTTree.Branch(name+"mM2_ep2enPiX", &paraDVpipP.mM2ep2enPiX, name+"mM2_ep2enPiX/F");
    		myTTree.Branch(name+"mP_ep2enPiX", &paraDVpipP.mPep2enPiX, name+"mP_ep2enPiX/F");
    		myTTree.Branch(name+"mM2_ep2enX", &paraDVpipP.mM2ep2enX, name+"mM2_ep2enX/F");
    		myTTree.Branch(name+"mP_ep2enX", &paraDVpipP.mPep2enX, name+"mP_ep2enX/F");
    		myTTree.Branch(name+"mM2_ep2ePiX", &paraDVpipP.mM2ep2ePiX, name+"mM2_ep2ePiX/F");
    		myTTree.Branch(name+"mP_ep2ePiX", &paraDVpipP.mPep2ePiX, name+"mP_ep2ePiX/F");
    		myTTree.Branch(name+"mM2_ep2nPiX", &paraDVpipP.mM2ep2nPiX, name+"mM2_ep2nPiX/F");
    		myTTree.Branch(name+"mP_ep2nPiX", &paraDVpipP.mPep2nPiX, name+"mP_ep2nPiX/F");
    		myTTree.Branch(name+"phi_nu_virPh", &paraDVpipP.phiNuVirPh, name+"phi_nu_virPh/F");
    		myTTree.Branch(name+"phi_nu_outPi", &paraDVpipP.phiNuOutPi, name+"phi_nu_outPi/F");
    		myTTree.Branch(name+"delta_phi", &paraDVpipP.deltaPhi, name+"delta_phi/F");
    		myTTree.Branch(name+"theta_misPi_pi", &paraDVpipP.thetaMisPiPi, name+"theta_misPi_pi/F");
    		myTTree.Branch(name+"theta_misNu_nu", &paraDVpipP.thetaMisNuNu, name+"theta_misNu_nu/F");
    		myTTree.Branch(name+"theta_el_pi", &paraDVpipP.thetaElPi, name+"theta_el_pi/F");
    		myTTree.Branch(name+"theta_el_nu", &paraDVpipP.thetaElNu, name+"theta_el_nu/F");
    		myTTree.Branch(name+"theta_pi_nu", &paraDVpipP.thetaPiNu, name+"theta_pi_nu/F");
    		myTTree.Branch(name+"exclusive_4DChi2", &paraDVpipP.excl4DChi2, name+"exclusive_4DChi2/F");
		};
		void addDVpipPnoNBranch(TString name, DVpipPnoN& paraDVpipPnoN) {
    		myTTree.Branch(name+"misNu_px", &paraDVpipPnoN.misNuPx, name+"misNu_px/F");
    		myTTree.Branch(name+"misNu_py", &paraDVpipPnoN.misNuPy, name+"misNu_py/F");
    		myTTree.Branch(name+"misNu_pz", &paraDVpipPnoN.misNuPz, name+"misNu_pz/F");
    		myTTree.Branch(name+"misNu_M", &paraDVpipPnoN.misNuM, name+"misNu_M/F");
    		myTTree.Branch(name+"misNu_P", &paraDVpipPnoN.misNuP, name+"misNu_P/F");
    		myTTree.Branch(name+"misNu_E", &paraDVpipPnoN.misNuE, name+"misNu_E/F");
    		myTTree.Branch(name+"misNu_phi", &paraDVpipPnoN.misNuPhi, name+"misNu_phi/F");
    		myTTree.Branch(name+"misNu_theta", &paraDVpipPnoN.misNuTheta, name+"misNu_theta/F");
    		myTTree.Branch(name+"Q2", &paraDVpipPnoN.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraDVpipPnoN.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraDVpipPnoN.Xbj, name+"Xbj/F");
    		myTTree.Branch(name+"t", &paraDVpipPnoN.t, name+"t/F");
    		myTTree.Branch(name+"phi", &paraDVpipPnoN.phi, name+"phi/F");
    		myTTree.Branch(name+"mM2_ep2ePiX", &paraDVpipPnoN.mM2ep2ePiX, name+"mM2_ep2ePiX/F");
    		myTTree.Branch(name+"mP_ep2ePiX", &paraDVpipPnoN.mPep2ePiX, name+"mP_ep2ePiX/F");
    		myTTree.Branch(name+"theta_el_pi", &paraDVpipPnoN.thetaElPi, name+"theta_el_pi/F");
		};
		void addDVpipiPBranch(TString name, DVpipiP& paraDVpipiP) {
    		myTTree.Branch(name+"Q2", &paraDVpipiP.Q2, name+"Q2/F");
    		myTTree.Branch(name+"W", &paraDVpipiP.W, name+"W/F");
    		myTTree.Branch(name+"Xbj", &paraDVpipiP.Xbj, name+"Xbj/F");
    		myTTree.Branch(name+"t_nucleon", &paraDVpipiP.tNucleon, name+"t_nucleon/F");
    		myTTree.Branch(name+"t_photon", &paraDVpipiP.tPhoton, name+"t_photon/F");
    		myTTree.Branch(name+"delta_t", &paraDVpipiP.deltaT, name+"delta_t/F");
    		myTTree.Branch(name+"mM2_ep2epPiPiX", &paraDVpipiP.mM2ep2epPiPiX, name+"mM2_ep2epPiPiX/F");
    		myTTree.Branch(name+"mP_ep2epPiPiX", &paraDVpipiP.mPep2epPiPiX, name+"mP_ep2epPiPiX/F");
    		myTTree.Branch(name+"mE_ep2epPiPiX", &paraDVpipiP.mEep2epPiPiX, name+"mE_ep2epPiPiX/F");
    		myTTree.Branch(name+"mPx_ep2epPiPiX", &paraDVpipiP.mPXep2epPiPiX, name+"mPx_ep2epPiPiX/F");
    		myTTree.Branch(name+"mPy_ep2epPiPiX", &paraDVpipiP.mPYep2epPiPiX, name+"mPy_ep2epPiPiX/F");
    		myTTree.Branch(name+"mPz_ep2epPiPiX", &paraDVpipiP.mPZep2epPiPiX, name+"mPz_ep2epPiPiX/F");
    		myTTree.Branch(name+"mM2_ep2epPipX", &paraDVpipiP.mM2ep2epPipX, name+"mM2_ep2epPipX/F");
    		myTTree.Branch(name+"mP_ep2epPipX", &paraDVpipiP.mPep2epPipX, name+"mP_ep2epPipX/F");
    		myTTree.Branch(name+"mM2_ep2epPimX", &paraDVpipiP.mM2ep2epPimX, name+"mM2_ep2epPimX/F");
    		myTTree.Branch(name+"mP_ep2epPimX", &paraDVpipiP.mPep2epPimX, name+"mP_ep2epPimX/F");
    		myTTree.Branch(name+"mM2_ep2ePiPiX", &paraDVpipiP.mM2ep2ePiPiX, name+"mM2_ep2ePiPiX/F");
    		myTTree.Branch(name+"mP_ep2ePiPiX", &paraDVpipiP.mPep2ePiPiX, name+"mP_ep2ePiPiX/F");
    		myTTree.Branch(name+"mM2_ep2pPiPiX", &paraDVpipiP.mM2ep2pPiPiX, name+"mM2_ep2pPiPiX/F");
    		myTTree.Branch(name+"mP_ep2pPiPiX", &paraDVpipiP.mPep2pPiPiX, name+"mP_ep2pPiPiX/F");
    		myTTree.Branch(name+"phi_nu_virPh", &paraDVpipiP.phiNuVirPh, name+"phi_nu_virPh/F");
    		myTTree.Branch(name+"phi_nu_outPi", &paraDVpipiP.phiNuOutPi, name+"phi_nu_outPi/F");
    		myTTree.Branch(name+"delta_phi", &paraDVpipiP.deltaPhi, name+"delta_phi/F");
    		myTTree.Branch(name+"theta_misPip_pip", &paraDVpipiP.thetaMisPipPip, name+"theta_misPip_pip/F");
    		myTTree.Branch(name+"theta_misPim_pim", &paraDVpipiP.thetaMisPimPim, name+"theta_misPim_pim/F");
    		myTTree.Branch(name+"theta_misNu_nu", &paraDVpipiP.thetaMisNuNu, name+"theta_misNu_nu/F");
    		myTTree.Branch(name+"theta_el_pip", &paraDVpipiP.thetaElPip, name+"theta_el_pip/F");
    		myTTree.Branch(name+"theta_el_pim", &paraDVpipiP.thetaElPim, name+"theta_el_pim/F");
    		myTTree.Branch(name+"theta_el_nu", &paraDVpipiP.thetaElNu, name+"theta_el_nu/F");
    		myTTree.Branch(name+"theta_pip_nu", &paraDVpipiP.thetaPipNu, name+"theta_pip_nu/F");
    		myTTree.Branch(name+"theta_pim_nu", &paraDVpipiP.thetaPimNu, name+"theta_pim_nu/F");
    		myTTree.Branch(name+"exclusive_4DChi2", &paraDVpipiP.excl4DChi2, name+"exclusive_4DChi2/F");
		};
		void addElDeteBranch(TString name, elDeteInfo& paraDete) {
			myTTree.Branch(name+"_CAL_sector", &paraDete.sectorCAL, name+"_CAL_sector[3]/I");
			myTTree.Branch(name+"_CAL_energy", &paraDete.energyCAL, name+"_CAL_energy[3]/F");
			myTTree.Branch(name+"_CAL_x", &paraDete.xCAL, name+"_CAL_x[3]/F");
			myTTree.Branch(name+"_CAL_y", &paraDete.yCAL, name+"_CAL_y[3]/F");
			myTTree.Branch(name+"_CAL_z", &paraDete.zCAL, name+"_CAL_z[3]/F");
			myTTree.Branch(name+"_CAL_lu", &paraDete.luCAL, name+"_CAL_lu[3]/F");
			myTTree.Branch(name+"_CAL_lv", &paraDete.lvCAL, name+"_CAL_lv[3]/F");
			myTTree.Branch(name+"_CAL_lw", &paraDete.lwCAL, name+"_CAL_lw[3]/F");
			myTTree.Branch(name+"_CAL_phi", &paraDete.phiCAL, name+"_CAL_phi[3]/F");
			myTTree.Branch(name+"_CAL_theta", &paraDete.thetaCAL, name+"_CAL_theta[3]/F");
			myTTree.Branch(name+"_CAL_time", &paraDete.timeCAL, name+"_CAL_time[3]/F");
			myTTree.Branch(name+"_CAL_path", &paraDete.pathCAL, name+"_CAL_path[3]/F");
			myTTree.Branch(name+"_CAL_energySum", &paraDete.energySumCAL, name+"_CAL_energySum/F");
			myTTree.Branch(name+"_DC_sector", &paraDete.sectorDC, name+"_DC_sector[3]/I");
			myTTree.Branch(name+"_DC_x", &paraDete.xDC, name+"_DC_x[3]/F");
			myTTree.Branch(name+"_DC_y", &paraDete.yDC, name+"_DC_y[3]/F");
			myTTree.Branch(name+"_DC_z", &paraDete.zDC, name+"_DC_z[3]/F");
			myTTree.Branch(name+"_DC_phi", &paraDete.phiDC, name+"_DC_phi[3]/F");
			myTTree.Branch(name+"_DC_theta", &paraDete.thetaDC, name+"_DC_theta[3]/F");
			myTTree.Branch(name+"_DC_edge", &paraDete.edgeDC, name+"_DC_edge[3]/F");
			myTTree.Branch(name+"_track_sector", &paraDete.sectorTrack, name+"_track_sector/I");
			myTTree.Branch(name+"_track_chi2", &paraDete.chi2Track, name+"_track_chi2/F");
			myTTree.Branch(name+"_track_ndf", &paraDete.ndfTrack, name+"_track_ndf/I");
			myTTree.Branch(name+"_track_chi2ndf", &paraDete.chi2ndfTrack, name+"_track_chi2ndf/F");
			myTTree.Branch(name+"_radPh_nPh", &paraDete.nPh, name+"_radPh_nPh/I");
			myTTree.Branch(name+"_radPh_num", &paraDete.num, name+"_radPh_num/I");
			myTTree.Branch(name+"_radPh_pindex", &paraDete.pindexPh, name+"_radPh_pindex["+name+"_radPh_num]/I");
			myTTree.Branch(name+"_radPh_P", &paraDete.pPh, name+"_radPh_P["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_px", &paraDete.pxPh, name+"_radPh_px["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_py", &paraDete.pyPh, name+"_radPh_py["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_pz", &paraDete.pzPh, name+"_radPh_pz["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_angle", &paraDete.anglePh, name+"_radPh_angle["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_dTheta", &paraDete.dThetaPh, name+"_radPh_dTheta["+name+"_radPh_num]/F");
			myTTree.Branch(name+"_radPh_dPhi", &paraDete.dPhiPh, name+"_radPh_dPhi["+name+"_radPh_num]/F");
		};
		void addNuDeteBranch(TString name, nuDeteInfo& paraDete, Int_t isProton) {
			myTTree.Branch(name+"_CND_nLayer", &paraDete.nLayerCND, name+"_CND_nLayer/I");
			myTTree.Branch(name+"_CND_lastLayer", &paraDete.lastLayerCND, name+"_CND_lastLayer/I");
			myTTree.Branch(name+"_SciCD_layer", &paraDete.layerSciCD, name+"_SciCD_layer[4]/I");
			myTTree.Branch(name+"_SciCD_energy", &paraDete.energySciCD, name+"_SciCD_energy[4]/F");
			myTTree.Branch(name+"_SciCD_x", &paraDete.xSciCD, name+"_SciCD_x[4]/F");
			myTTree.Branch(name+"_SciCD_y", &paraDete.ySciCD, name+"_SciCD_y[4]/F");
			myTTree.Branch(name+"_SciCD_z", &paraDete.zSciCD, name+"_SciCD_z[4]/F");
			myTTree.Branch(name+"_SciCD_phi", &paraDete.phiSciCD, name+"_SciCD_phi[4]/F");
			myTTree.Branch(name+"_SciCD_theta", &paraDete.thetaSciCD, name+"_SciCD_theta[4]/F");
			myTTree.Branch(name+"_SciCD_time", &paraDete.timeSciCD, name+"_SciCD_time[4]/F");
			myTTree.Branch(name+"_SciCD_path", &paraDete.pathSciCD, name+"_SciCD_path[4]/F");
			myTTree.Branch(name+"_SciCD_dedx", &paraDete.dedxSciCD, name+"_SciCD_dedx[4]/F");
			myTTree.Branch(name+"_SciCD_size", &paraDete.sizeSciCD, name+"_SciCD_size[4]/I");
			myTTree.Branch(name+"_SciCD_layermult", &paraDete.layermultSciCD, name+"_SciCD_layermult[4]/I");
			myTTree.Branch(name+"_CAL_sector", &paraDete.sectorCAL, name+"_CAL_sector[3]/I");
			myTTree.Branch(name+"_CAL_energy", &paraDete.energyCAL, name+"_CAL_energy[3]/F");
			myTTree.Branch(name+"_CAL_x", &paraDete.xCAL, name+"_CAL_x[3]/F");
			myTTree.Branch(name+"_CAL_y", &paraDete.yCAL, name+"_CAL_y[3]/F");
			myTTree.Branch(name+"_CAL_z", &paraDete.zCAL, name+"_CAL_z[3]/F");
			myTTree.Branch(name+"_CAL_lu", &paraDete.luCAL, name+"_CAL_lu[3]/F");
			myTTree.Branch(name+"_CAL_lv", &paraDete.lvCAL, name+"_CAL_lv[3]/F");
			myTTree.Branch(name+"_CAL_lw", &paraDete.lwCAL, name+"_CAL_lw[3]/F");
			myTTree.Branch(name+"_CAL_phi", &paraDete.phiCAL, name+"_CAL_phi[3]/F");
			myTTree.Branch(name+"_CAL_theta", &paraDete.thetaCAL, name+"_CAL_theta[3]/F");
			myTTree.Branch(name+"_CAL_time", &paraDete.timeCAL, name+"_CAL_time[3]/F");
			myTTree.Branch(name+"_CAL_path", &paraDete.pathCAL, name+"_CAL_path[3]/F");
			myTTree.Branch(name+"_CAL_energySum", &paraDete.energySumCAL, name+"_CAL_energySum/F");
			if (isProton) {
				myTTree.Branch(name+"_DC_sector", &paraDete.sectorDC, name+"_DC_sector[3]/I");
				myTTree.Branch(name+"_DC_x", &paraDete.xDC, name+"_DC_x[3]/F");
				myTTree.Branch(name+"_DC_y", &paraDete.yDC, name+"_DC_y[3]/F");
				myTTree.Branch(name+"_DC_z", &paraDete.zDC, name+"_DC_z[3]/F");
				myTTree.Branch(name+"_DC_phi", &paraDete.phiDC, name+"_DC_phi[3]/F");
				myTTree.Branch(name+"_DC_theta", &paraDete.thetaDC, name+"_DC_theta[3]/F");
				myTTree.Branch(name+"_DC_edge", &paraDete.edgeDC, name+"_DC_edge[3]/F");
			}
		};
		void addPhDeteBranch(TString name, phDeteInfo& paraDete) {
			myTTree.Branch(name+"_CAL_sector", &paraDete.sectorCAL, name+"_CAL_sector[3]/I");
			myTTree.Branch(name+"_CAL_energy", &paraDete.energyCAL, name+"_CAL_energy[3]/F");
			myTTree.Branch(name+"_CAL_x", &paraDete.xCAL, name+"_CAL_x[3]/F");
			myTTree.Branch(name+"_CAL_y", &paraDete.yCAL, name+"_CAL_y[3]/F");
			myTTree.Branch(name+"_CAL_z", &paraDete.zCAL, name+"_CAL_z[3]/F");
			myTTree.Branch(name+"_CAL_lu", &paraDete.luCAL, name+"_CAL_lu[3]/F");
			myTTree.Branch(name+"_CAL_lv", &paraDete.lvCAL, name+"_CAL_lv[3]/F");
			myTTree.Branch(name+"_CAL_lw", &paraDete.lwCAL, name+"_CAL_lw[3]/F");
			myTTree.Branch(name+"_CAL_phi", &paraDete.phiCAL, name+"_CAL_phi[3]/F");
			myTTree.Branch(name+"_CAL_theta", &paraDete.thetaCAL, name+"_CAL_theta[3]/F");
			myTTree.Branch(name+"_CAL_time", &paraDete.timeCAL, name+"_CAL_time[3]/F");
			myTTree.Branch(name+"_CAL_path", &paraDete.pathCAL, name+"_CAL_path[3]/F");
			myTTree.Branch(name+"_CAL_energySum", &paraDete.energySumCAL, name+"_CAL_energySum/F");
			myTTree.Branch(name+"_FT_x", &paraDete.xFT, name+"_FT_x/F");
			myTTree.Branch(name+"_FT_y", &paraDete.yFT, name+"_FT_y/F");
			myTTree.Branch(name+"_FT_z", &paraDete.zFT, name+"_FT_z/F");
			myTTree.Branch(name+"_FT_energy", &paraDete.energyFT, name+"_FT_energy/F");
		};
		void addCVTBranch(CVTInfo& paraDete) {
			myTTree.Branch("CVT_nTrack", &paraDete.nTrack, "CVT_nTrack/I");
			myTTree.Branch("CVT_nCluster", &paraDete.nCluster, "CVT_nCluster/I");
			myTTree.Branch("CVT_num", &paraDete.num, "CVT_num/I");
			myTTree.Branch("CVT_pindex", &paraDete.pindexCVT, "CVT_pindex[CVT_num]/I");
			myTTree.Branch("CVT_pid", &paraDete.pidCVT, "CVT_pid[CVT_num]/I");
			myTTree.Branch("CVT_layer", &paraDete.layerCVT, "CVT_layer[CVT_num]/I");
			myTTree.Branch("CVT_x", &paraDete.xCVT, "CVT_x[CVT_num]/F");
			myTTree.Branch("CVT_y", &paraDete.yCVT, "CVT_y[CVT_num]/F");
			myTTree.Branch("CVT_z", &paraDete.zCVT, "CVT_z[CVT_num]/F");
			myTTree.Branch("CVT_phi", &paraDete.phiCVT, "CVT_phi[CVT_num]/F");
			myTTree.Branch("CVT_theta", &paraDete.thetaCVT, "CVT_theta[CVT_num]/F");
		};
		void addCTOFBranch(CTOFInfo& paraDete) {
			myTTree.Branch("CTOF_nCluster", &paraDete.nCluster, "CTOF_nCluster/I");
			myTTree.Branch("CTOF_num", &paraDete.num, "CTOF_num/I");
			myTTree.Branch("CTOF_pindex", &paraDete.pindexCTOF, "CTOF_pindex[CTOF_num]/I");
			myTTree.Branch("CTOF_pid", &paraDete.pidCTOF, "CTOF_pid[CTOF_num]/I");
			myTTree.Branch("CTOF_layer", &paraDete.layerCTOF, "CTOF_layer[CTOF_num]/I");
			myTTree.Branch("CTOF_energy", &paraDete.energyCTOF, "CTOF_energy[CTOF_num]/F");
			myTTree.Branch("CTOF_x", &paraDete.xCTOF, "CTOF_x[CTOF_num]/F");
			myTTree.Branch("CTOF_y", &paraDete.yCTOF, "CTOF_y[CTOF_num]/F");
			myTTree.Branch("CTOF_z", &paraDete.zCTOF, "CTOF_z[CTOF_num]/F");
			myTTree.Branch("CTOF_t", &paraDete.tCTOF, "CTOF_t[CTOF_num]/F");
			myTTree.Branch("CTOF_phi", &paraDete.phiCTOF, "CTOF_phi[CTOF_num]/F");
			myTTree.Branch("CTOF_theta", &paraDete.thetaCTOF, "CTOF_theta[CTOF_num]/F");
			myTTree.Branch("CTOF_dedx", &paraDete.dedxCTOF, "CTOF_dedx[CTOF_num]/F");
			myTTree.Branch("CTOF_size", &paraDete.sizeCTOF, "CTOF_size[CTOF_num]/I");
			myTTree.Branch("CTOF_layermult", &paraDete.layermultCTOF, "CTOF_layermult[CTOF_num]/I");
		};
		void addCNDBranch(CNDInfo& paraDete) {
			myTTree.Branch("CND_nTrack", &paraDete.nTrack, "CND_nTrack/I");
			myTTree.Branch("CND_nCluster", &paraDete.nCluster, "CND_nCluster/I");
			myTTree.Branch("CND_num", &paraDete.num, "CND_num/I");
			myTTree.Branch("CND_pindex", &paraDete.pindexCND, "CND_pindex[CND_num]/I");
			myTTree.Branch("CND_pid", &paraDete.pidCND, "CND_pid[CND_num]/I");
			myTTree.Branch("CND_layer", &paraDete.layerCND, "CND_layer[CND_num]/I");
			myTTree.Branch("CND_energy", &paraDete.energyCND, "CND_energy[CND_num]/F");
			myTTree.Branch("CND_x", &paraDete.xCND, "CND_x[CND_num]/F");
			myTTree.Branch("CND_y", &paraDete.yCND, "CND_y[CND_num]/F");
			myTTree.Branch("CND_z", &paraDete.zCND, "CND_z[CND_num]/F");
			myTTree.Branch("CND_t", &paraDete.tCND, "CND_t[CND_num]/F");
			myTTree.Branch("CND_phi", &paraDete.phiCND, "CND_phi[CND_num]/F");
			myTTree.Branch("CND_theta", &paraDete.thetaCND, "CND_theta[CND_num]/F");
			myTTree.Branch("CND_dedx", &paraDete.dedxCND, "CND_dedx[CND_num]/F");
			myTTree.Branch("CND_size", &paraDete.sizeCND, "CND_size[CND_num]/I");
			myTTree.Branch("CND_layermult", &paraDete.layermultCND, "CND_layermult[CND_num]/I");
		};
		void addCALBranch(CALInfo& paraDete) {
			myTTree.Branch("CAL_nParticle", &paraDete.nParticle, "CAL_nParticle/I");
			myTTree.Branch("CAL_nNeutron", &paraDete.nNeutron, "CAL_nNeutron/I");
			myTTree.Branch("CAL_nNeutronNew", &paraDete.nNeutronNew, "CAL_nNeutronNew/I");
			myTTree.Branch("CAL_nCluster", &paraDete.nCluster, "CAL_nCluster/I");
			myTTree.Branch("CAL_num", &paraDete.num, "CAL_num/I");
			myTTree.Branch("CAL_pindex", &paraDete.pindexCAL, "CAL_pindex[CAL_num]/I");
			myTTree.Branch("CAL_pid", &paraDete.pidCAL, "CAL_pid[CAL_num]/I");
			myTTree.Branch("CAL_layer", &paraDete.layerCAL, "CAL_layer[CAL_num]/I");
			myTTree.Branch("CAL_sector", &paraDete.sectorCAL, "CAL_sector[CAL_num]/I");
			myTTree.Branch("CAL_energy", &paraDete.energyCAL, "CAL_energy[CAL_num]/F");
			myTTree.Branch("CAL_time", &paraDete.timeCAL, "CAL_time[CAL_num]/F");
			myTTree.Branch("CAL_path", &paraDete.pathCAL, "CAL_path[CAL_num]/F");
			myTTree.Branch("CAL_x", &paraDete.xCAL, "CAL_x[CAL_num]/F");
			myTTree.Branch("CAL_y", &paraDete.yCAL, "CAL_y[CAL_num]/F");
			myTTree.Branch("CAL_z", &paraDete.zCAL, "CAL_z[CAL_num]/F");
		};
		TTree myTTree;
};

#endif
